### ISSUE TITLE
Source code of "HTTP + JSON" version

### ISSUE THREAD

**Issue by skatsuta** [matope/grpc-kvs#1]
Hi, I've read your blog post (http://matope.hatenablog.com/entry/2016/01/05/003234) with great interest.

I'm also measuring the performance of gRPC now to decide whether to use it in our new microservices, and in my local environment my simple benchmarks say gRPC is faster than HTTP+JSON or MessagePack RPC.

Since I wanna reproduce your benchmark results by myself, I want the complete "HTTP + JSON" version of the program.

Could you publish it too? Thank you.

**Comment by matope** [comment]
Thank you for your interest.
The source code for HTTP+JSON server is in bench/http.go.

And these the steps to run my benchmarks.

## To bench HTTP+JSON

``` bash
// In http mode, benchmark program invoke http-server by itself.

$ go run bench/main.go bench/http.go http
Waiting for workers...
10000 jobs in 0.28 seconds (36026.70 jobs/sec)
```

## To bench gRPC

``` bash
// To benchmark grpc, you have to invoke grpc server previously by yourself.
$ go run server/main.go

(In another shell)

$ go run bench/main.go bench/http.go grpc
Waiting for workers...
10000 jobs in 0.61 seconds (16385.26 jobs/sec)
```

Actually, I'm a little skeptical about my result too but I couldn't find any mistakes by myself.
So, please let me know if you could find any interesting things.

**Comment by skatsuta** [comment]
@matope Thank you! Sorry I haven't noticed it's already there. I'll try it!
